### ISSUE TITLE
Hello, can the code for using this map for navigation be open source? Look forward to your reply, thank you!

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [g-ch/DSP-map#2]
Hello, can the code for using this map for navigation be open source? Look forward to your reply, thank you!

**Comment by g-ch** [comment]
I am so sorry for the very late reply. The message was somehow missed. An example of using this map for motion planning can be found [here](https://github.com/tud-amr/RAST_corridor_planning). We also recommend checking the [upgraded version](https://github.com/tud-amr/semantic_dsp_map) of this map.
